// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Badge

#include "../ui.h"

void ui_badgeScreen_screen_init(void)
{
    ui_badgeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_badgeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_badgeScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_badgeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badgePanel = lv_obj_create(ui_badgeScreen);
    lv_obj_set_width(ui_badgePanel, 250);
    lv_obj_set_height(ui_badgePanel, 122);
    lv_obj_set_align(ui_badgePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_badgePanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_badgePanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_badgePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_badgePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_badgePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_badgePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_badgePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_badgePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_badgePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_badgePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_badgePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nameText = lv_label_create(ui_badgePanel);
    lv_obj_set_width(ui_nameText, 230);
    lv_obj_set_height(ui_nameText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_nameText, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_nameText, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_nameText, "Felix Biego");
    lv_obj_set_style_text_font(ui_nameText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleText = lv_label_create(ui_badgePanel);
    lv_obj_set_width(ui_titleText, 230);
    lv_obj_set_height(ui_titleText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titleText, 1);
    lv_obj_set_y(ui_titleText, -23);
    lv_obj_set_align(ui_titleText, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_titleText, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_titleText, "Embedded Software Developer");

    ui_emailText = lv_label_create(ui_badgePanel);
    lv_obj_set_width(ui_emailText, 230);
    lv_obj_set_height(ui_emailText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_emailText, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_emailText, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_emailText, "fbiego.fb@gmail.com");

    ui_barCode = lv_barcode_create(ui_badgePanel);
    // lv_obj_set_width(ui_barCode, 250);
    lv_obj_set_height(ui_barCode, 50);
    lv_obj_set_align(ui_barCode, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_barCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_barCode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barCode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_barcode_set_dark_color(ui_barCode , lv_color_make(0, 0, 0));
    lv_barcode_set_light_color(ui_barCode , lv_color_make(255, 255, 255));
    lv_barcode_update(ui_barCode, "https://lvgl.io");


}
